


PROC SQL NOPRINT;
CREATE TABLE SELIC AS
SELECT DISTINCT SELIC,YEAR(DATAX) AS ANO,MONTH(DATAX) AS MES 
FROM REC.SELIC;

CREATE TABLE TJLP AS
SELECT DISTINCT TJLP,YEAR(DATAX) AS ANO,MONTH(DATAX) AS MES 
FROM REC.TJLP;

CREATE TABLE TLP AS
SELECT DISTINCT TLP,YEAR(DATA) AS ANO,MONTH(DATA) AS MES 
FROM REC.TLP;
QUIT;


PROC SQL NOPRINT;
CREATE TABLE TEMP AS
SELECT Custo_Financeiro,
       COUNT(*) AS TOTAL
FROM REC.BNDES 
GROUP BY Custo_Financeiro;
QUIT;


PROC SQL NOPRINT;
CREATE TABLE RAROC AS
SELECT DISTINCT A.CNPJ,A.EMPRESA,A.DATA_CONTRATO,A.VALOR_CONTRATO AS VALOR_OPERACOES,
       A.VALOR_DESEMBOLSO,A.PRAZO_AMORTIZACAO AS PRAZO,A.PRAZO_CARENCIA,B.PROB,B.RISCOBC,C.SELIC AS SELIC,
	   CASE WHEN CUSTO_FINANCEIRO LIKE "%SELIC%" THEN A.JUROS + C.SELIC
            WHEN CUSTO_FINANCEIRO LIKE "%TJLP%"  THEN A.JUROS + D.TJLP
			WHEN CUSTO_FINANCEIRO LIKE "%TJLP%"  THEN A.JUROS + E.TLP
            ELSE A.JUROS END AS TAXA_JUROS

FROM REC.BNDES AS A
INNER JOIN REC.BNDES_PROB AS B ON EMPRESA=CNPJ8 AND YEAR(A.DATA_CONTRATO)=ANO
INNER JOIN SELIC    AS C ON YEAR(A.DATA_CONTRATO)=C.ANO AND MONTH(A.DATA_CONTRATO)=C.MES
INNER JOIN TJLP     AS D ON YEAR(A.DATA_CONTRATO)=D.ANO AND MONTH(A.DATA_CONTRATO)=D.MES
INNER JOIN TLP      AS E ON YEAR(A.DATA_CONTRATO)=E.ANO AND MONTH(A.DATA_CONTRATO)=E.MES;
QUIT;



PROC SQL NOPRINT;
CREATE TABLE RAROC AS
SELECT DISTINCT A.CNPJ,A.EMPRESA,A.DATA_CONTRATO,A.VALOR_CONTRATO AS VALOR_OPERACOES,
       A.VALOR_DESEMBOLSO,A.PRAZO_AMORTIZACAO AS PRAZO,B.PROB,B.RISCOBC,
	   CASE WHEN CUSTO_FINANCEIRO LIKE "%SELIC%" THEN A.JUROS/100 + C.SELIC/100
            WHEN CUSTO_FINANCEIRO LIKE "%TJLP%"  THEN A.JUROS/100 + D.TJLP/100
			WHEN CUSTO_FINANCEIRO LIKE "%TJLP%"  THEN A.JUROS/100 + E.TLP/100
            ELSE A.JUROS/100 END AS TAXA_JUROS

FROM REC.BNDES AS A
INNER JOIN REC.BNDES_PROB AS B ON EMPRESA=CNPJ8 AND YEAR(A.DATA_CONTRATO)=ANO
INNER JOIN SELIC     AS C ON YEAR(A.DATA_CONTRATO)=C.ANO AND MONTH(A.DATA_CONTRATO)=C.MES
INNER JOIN TJLP      AS D ON YEAR(A.DATA_CONTRATO)=D.ANO AND MONTH(A.DATA_CONTRATO)=D.MES
INNER JOIN TLP       AS E ON YEAR(A.DATA_CONTRATO)=E.ANO AND MONTH(A.DATA_CONTRATO)=E.MES;
QUIT;


/*----------------------------------------------------------------------*/
/*---          RAROC DA CARTEIRA DE FINANCIAMENTO DE BNDES           ---*/
/*---------------------------------------------------------------------*/


PROC MEANS DATA=RAROC NOPRINT NWAY;
CLASS RISCOBC;
OUTPUT OUT=PD(DROP=_TYPE_ _FREQ_) MEDIAN(PROB)=PD P99(PROB)=QPROV99;
RUN;



DATA PD2;
INPUT RISCOBC $ PD QPROV99;
CARDS;
AA 0.0022 0.03
A  0.0070 0.10
B  0.0103 0.30
C  0.0546 0.50
D  0.2000 0.50
E  0.4000 0.70
F  0.6000 1.00
G  0.8500 1.20
H  1.0000 1.40
;
RUN;



PROC SQL NOPRINT;
CREATE TABLE RAROC2 AS
SELECT DISTINCT A.*,B.PD,B.QPROV99
FROM RAROC AS A
INNER JOIN PD AS B ON A.RISCOBC=B.RISCOBC;
QUIT;


DATA RAROC3;SET RAROC2;
/*VALOR_OPERACOES     = 35000;*/
GARANTIA              = 0.75;
VALOR_FINAL           = VALOR_OPERACOES*((1+TAXA_JUROS)**PRAZO);
PRESTACAO_FORMULA     = VALOR_OPERACOES*((((1+TAXA_JUROS)**PRAZO)*TAXA_JUROS)/(((1+TAXA_JUROS)**PRAZO)-1));
PRESTACAO_PRICE       = FINANCE('pmt',TAXA_JUROS,PRAZO,-VALOR_OPERACOES,0);
SELIC                 = (SELIC/12)/100;
SELIC_PRAZO           = ((1+SELIC)**(PRAZO+PRAZO_CARENCIA))-1;
CUSTO_CAPTACAO        = VALOR_OPERACOES*(1+SELIC_PRAZO);
MONTANTE_NOMINAL      = PRAZO*PRESTACAO_PRICE;
CUSTOS_OPER           = 0.03*MONTANTE_NOMINAL;
PD                    = PD*(1+0.27)**((PRAZO+PRAZO_CARENCIA)*0.27);
DESVIO_PERDA_ESPERADA = QPROV99*(1-GARANTIA)*MONTANTE_NOMINAL;
PERDA_ESPERADA        = PD*MONTANTE_NOMINAL;
SPREAD                = MONTANTE_NOMINAL-CUSTO_CAPTACAO;
LUCRO_AJUSTADO        = SPREAD-CUSTOS_OPER-PERDA_ESPERADA;
VAR                   = PERDA_ESPERADA+(1-GARANTIA)*DESVIO_PERDA_ESPERADA;
RAROC                 = LUCRO_AJUSTADO/VAR;
RUN;



PROC SORT DATA=RAROC3;BY RISCOBC;RUN;
PROC MEANS DATA=RAROC3 NOPRINT;
BY RISCOBC;
OUTPUT OUT=DIST 
P1(RAROC)=RAROC_1 P25(RAROC)=RAROC_P25P25(RAROC)=RAROC_P25 P50(RAROC)=RAROC_MED P75(RAROC)=RAROC_P75 P99(PROB)=RAROC_99;
RUN;


PROC SORT DATA=RAROC3;BY RISCOBC;RUN;
PROC MEANS DATA=RAROC3 NOPRINT;
BY RISCOBC;
OUTPUT OUT=DIST 
SUM(VAR)=VAR_ MEAN(PROB)=PROB MEAN(PD)=PD;
RUN;



