LIBNAME REC "/dados/RISCO/Modelagem_Nas/Risco_de_Credito/Fraude/Receita";

PROC CONTENTS DATA=REC.ADMIN_PUBLICA OUT=C(KEEP=NAME) NOPRINT;RUN;
PROC CONTENTS DATA=REC.NAOAUTOMATICAS OUT=C(KEEP=NAME) NOPRINT;RUN;



/*CONFERENCIA DE DADOS*/
PROC SQL NOPRINT;
CREATE TABLE TEMP0 AS
SELECT COUNT(*) AS TOTAL,1 AS BASE
FROM RECEITA.INDIRETAS_AUTOMATICAS AS A
UNION
SELECT COUNT(*) AS TOTAL,2 AS BASE
FROM RECEITA.BNDES;
QUIT;


/*ESTATISTICA POR PORTE DE EMPRESA*/
PROC SQL NOPRINT;
CREATE TABLE TEMP1 AS
SELECT PORTE_EMPRESA,'BNDES' AS TIPO,
       COUNT(*) AS TOTAL,
       SUM(VR_CPT_SOC) AS VR_CPT_SOC
FROM RECEITA.TB_RFB_EMPRESA AS A
WHERE NUMCNPJ_RAIZ IN (SELECT DISTINCT EMPRESA FROM RECEITA.BNDES)
GROUP BY PORTE_EMPRESA
UNION
SELECT PORTE_EMPRESA,'DEMAIS' AS TIPO,
       COUNT(*) AS TOTAL,
       SUM(VR_CPT_SOC) AS VR_CPT_SOC
FROM RECEITA.TB_RFB_EMPRESA AS A
WHERE NUMCNPJ_RAIZ NOT IN (SELECT DISTINCT EMPRESA FROM RECEITA.BNDES)
GROUP BY PORTE_EMPRESA
ORDER BY TIPO,PORTE_EMPRESA;
QUIT;



/*ESTATISTICA POR QUAL_RESPO*/
PROC SQL NOPRINT;
CREATE TABLE TEMP2 AS
SELECT QUAL_RESPO,'BNDES' AS TIPO,
       COUNT(*) AS TOTAL,
       SUM(VR_CPT_SOC) AS VR_CPT_SOC
FROM RECEITA.TB_RFB_EMPRESA AS A
WHERE NUMCNPJ_RAIZ IN (SELECT DISTINCT EMPRESA FROM RECEITA.BNDES)
GROUP BY QUAL_RESPO
UNION
SELECT QUAL_RESPO,'DEMAIS' AS TIPO,
       COUNT(*) AS TOTAL,
       SUM(VR_CPT_SOC) AS VR_CPT_SOC
FROM RECEITA.TB_RFB_EMPRESA AS A
WHERE NUMCNPJ_RAIZ NOT IN (SELECT DISTINCT EMPRESA FROM RECEITA.BNDES)
GROUP BY QUAL_RESPO
ORDER BY TIPO,QUAL_RESPO;
QUIT;



/*
INTCK('MONTHS',DATA_SITUACAO,'01MAR2023'd) AS SITUACAO,
INTCK('MONTHS',DT_INICIO    ,'01MAR2023'd) AS IDADE
*/

PROC SQL NOPRINT;
CREATE TABLE DATA_SIT(COMPRESS=YES) AS
SELECT CNPJBASICO,
       MAX(DATA_SIT) AS DATA_MAX FORMAT=DATE9.,
       MIN(DATA_SIT) AS DATA_MIN FORMAT=DATE9.
FROM RECEITA.TB_RFB_FILIAIS 
GROUP BY CNPJBASICO;
QUIT;


/*TODAY()*/
PROC SQL NOPRINT;
CREATE TABLE FILIAIS(COMPRESS=YES) AS
SELECT DISTINCT A.CNPJBASICO,SIT_CADASTRAL,VR_CPT_SOC,PORTE_EMPRESA,DATA_SIT,
       INTCK('MONTHS',DATA_SIT,'01MAR2023'd) AS IDADE_SIT

FROM RECEITA.TB_RFB_FILIAIS AS A
LEFT JOIN RECEITA.TB_RFB_EMPRESA AS B ON A.CNPJBASICO=B.NUMCNPJ_RAIZ
INNER JOIN DATA_SIT AS C ON A.CNPJBASICO=C.CNPJBASICO AND A.DATA_SIT=C.DATA_MAX;
QUIT;





PROC SQL NOPRINT;
CREATE TABLE TEMP3 AS
SELECT SIT_CADASTRAL,'BNDES' AS TIPO,
       COUNT(*) AS TOTAL,
       AVG(IDADE_SIT) AS IDADE_SIT
FROM FILIAIS AS A
WHERE CNPJBASICO IN (SELECT DISTINCT EMPRESA FROM RECEITA.BNDES)
GROUP BY SIT_CADASTRAL
UNION
SELECT SIT_CADASTRAL,'DEMAIS' AS TIPO,
       COUNT(*) AS TOTAL,
       AVG(IDADE_SIT) AS IDADE_SIT
FROM FILIAIS AS A
WHERE CNPJBASICO NOT IN (SELECT DISTINCT EMPRESA FROM RECEITA.BNDES)
GROUP BY SIT_CADASTRAL
ORDER BY TIPO,SIT_CADASTRAL;
QUIT;




PROC SQL NOPRINT;
CREATE TABLE FILIAIS_BNDES(COMPRESS=YES) AS
SELECT DISTINCT A.CNPJBASICO,SIT_CADASTRAL,VR_CPT_SOC,PORTE_EMPRESA,DATA_SIT,
       INTCK('MONTHS',DATA_SIT,'01MAR2023'd) AS IDADE_SIT

FROM RECEITA.TB_RFB_FILIAIS AS A
LEFT JOIN RECEITA.TB_RFB_EMPRESA AS B ON A.CNPJBASICO=B.NUMCNPJ_RAIZ
INNER JOIN DATA_SIT AS C ON A.CNPJBASICO=C.CNPJBASICO AND A.DATA_SIT=C.DATA_MAX;
QUIT;




PROC SQL NOPRINT;
CREATE TABLE BNDES AS
SELECT EMPRESA,UF,CUSTO_FINANCEIRO,INOVACAO,FORMA_APOIO,SITUACAO_CONTRATO,YEAR(DATA_CONTRATO) AS ANO,
       COUNT(*) AS TOTAL,
       SUM(VALOR_CONTRATO) AS VALOR_CONTRATO,
	   SUM(VALOR_DESEMBOLSO) AS VALOR_CONTRATO,
	   AVG(PRAZO_CARENCIA) AS JUROS,
	   AVG(PRAZO_AMORTIZACAO) AS PRAZO_AMORTIZACAO

FROM RECEITA.BNDES
GROUP BY EMPRESA,UF,CUSTO_FINANCEIRO,INOVACAO,FORMA_APOIO,SITUACAO_CONTRATO,ANO;
QUIT;


LIBNAME REC "/dados/RISCO/Modelagem_Nas/Risco_de_Credito/Fraude/Receita";
DATA RECEITA.TB_RFB_EMPRESA(COMPRESS=YES);SET REC.TB_RFB_EMPRESA;
DT_CARGA='01MAY2022'd;
FORMAT DT_CARGA DATE9.;
RUN;

DATA RECEITA.TB_RFB_FILIAIS(COMPRESS=YES);SET REC.TB_RFB_FILIAIS;
DT_CARGA='01MAY2022'd;
FORMAT DT_CARGA DATE9.;
RUN;

DATA RECEITA.TB_RFB_SOCIOS(COMPRESS=YES);SET REC.TB_RFB_SOCIOS;
DT_CARGA='01MAY2022'd;
FORMAT DT_CARGA DATE9.;
RUN;