LIBNAME REC "/dados/RISCO/Modelagem_Nas/Risco_de_Credito/Fraude/Receita";

PROC CONTENTS DATA=REC.INDIRETAS_AUTOMATICAS OUT=C1(KEEP=NAME) NOPRINT;RUN;
PROC CONTENTS DATA=REC.BNDES_NAO_AUTOM       OUT=C2(KEEP=NAME) NOPRINT;RUN;


PROC SQL NOPRINT;
CREATE TABLE BNDES AS
SELECT CUSTO_FINANCEIRO,'BNDES_NAO_AUTOM' AS FONTE,
       COUNT(*) AS TOTAL,
       SUM(VALOR_CONTRATO) AS VALOR_CONTRATO,
	   SUM(PRAZO_CARENCIA) AS SOMA_JUROS

FROM REC.BNDES_NAO_AUTOM
GROUP BY CUSTO_FINANCEIRO
UNION
SELECT CUSTO_FINANCEIRO,'INDIRETAS_AUTOMATICAS' AS FONTE,
       COUNT(*) AS TOTAL,
       SUM(VALOR_CONTRATO) AS VALOR_CONTRATO,
	   SUM(PRAZO_CARENCIA) AS SOMA_JUROS

FROM REC.INDIRETAS_AUTOMATICAS
GROUP BY CUSTO_FINANCEIRO
ORDER BY CUSTO_FINANCEIRO;
QUIT;


/*https://www.bndes.gov.br/wps/portal/site/home/financiamento/guia/custos-financeiros/custo-financeiro*/
PROC SQL NOPRINT;
CREATE TABLE NAOAUTOM AS
SELECT DISTINCT CNPJ,JUROS,VALOR_CONTRATO,PRAZO_AMORTIZACAO,VALOR_DESEMBOLSO,PRAZO_CARENCIA,INOVACAO,
       PRAZO_AMORTIZACAO*VALOR_CONTRATO AS AMORTIZACAO_CONTRATO,
	   PRAZO_CARENCIA*VALOR_CONTRATO AS CARENCIA_CONTRATO,
       JUROS*VALOR_CONTRATO AS JUROS_CONTRATO,
	   MDY(MONTH(DATA_CONTRATO),1,YEAR(DATA_CONTRATO)) AS DATA_MOVIMENTO FORMAT=DATE9.,
       CASE WHEN CUSTO_FINANCEIRO LIKE '%TAXA FIXA%'   THEN 'FIXO'
	   	    WHEN CUSTO_FINANCEIRO LIKE '%TJ%'          THEN 'FIXO'
			WHEN CUSTO_FINANCEIRO LIKE '%TLP%'         THEN 'FIXO'
			ELSE 'VARIÁVEL' END AS CUSTO_FINANCEIRO	   
FROM REC.BNDES_NAO_AUTOM;

CREATE TABLE AUTOM AS
SELECT DISTINCT CNPJ,JUROS,VALOR_CONTRATO,PRAZO_AMORTIZACAO,VALOR_DESEMBOLSO,PRAZO_CARENCIA,INOVACAO,
       PRAZO_AMORTIZACAO*VALOR_CONTRATO AS AMORTIZACAO_CONTRATO,
	   PRAZO_CARENCIA*VALOR_CONTRATO AS CARENCIA_CONTRATO,
       JUROS*VALOR_CONTRATO AS JUROS_CONTRATO,
	   MDY(MONTH(DATA_CONTRATO),1,YEAR(DATA_CONTRATO)) AS DATA_MOVIMENTO FORMAT=DATE9.,
       CASE WHEN CUSTO_FINANCEIRO LIKE '%TAXA FIXA%'   THEN 'FIXO'
	   	    WHEN CUSTO_FINANCEIRO LIKE '%TJ%'          THEN 'FIXO'
			WHEN CUSTO_FINANCEIRO LIKE '%TLP%'         THEN 'FIXO'
			ELSE 'VARIÁVEL' END AS CUSTO_FINANCEIRO	   
FROM REC.INDIRETAS_AUTOMATICAS;
QUIT;


/*
PROC SQL NOPRINT;
CREATE TABLE BNDES1 AS
SELECT CUSTO_FINANCEIRO,
       COUNT(*) AS TOTAL	   

FROM BNDES
GROUP BY CUSTO_FINANCEIRO
ORDER BY CUSTO_FINANCEIRO;
QUIT;
*/



PROC SQL NOPRINT;
CREATE TABLE AUTOM2 AS
SELECT CUSTO_FINANCEIRO,
       DATA_MOVIMENTO,
       COUNT(*) AS TOTAL,
	   COUNT(DISTINCT CNPJ) AS TOTAL_CNPJ,
       SUM(VALOR_CONTRATO) AS VALOR_CONTRATO,
	   SUM(VALOR_DESEMBOLSO) AS VALOR_DESEMBOLSO,
	   SUM(JUROS_CONTRATO) AS JUROS_CONTRATO,
	   AVG(JUROS) AS JUROS,
	   SUM(JUROS_CONTRATO)/SUM(VALOR_CONTRATO) AS JUROS_PESO,
	   SUM(AMORTIZACAO_CONTRATO)/SUM(VALOR_CONTRATO) AS AMORTIZACAO_PESO,
	   AVG(PRAZO_AMORTIZACAO) AS PRAZO_AMORTIZACAO

FROM AUTOM
GROUP BY CUSTO_FINANCEIRO,DATA_MOVIMENTO
ORDER BY CUSTO_FINANCEIRO,DATA_MOVIMENTO;

CREATE TABLE NAOAUTOM2 AS
SELECT CUSTO_FINANCEIRO,
       DATA_MOVIMENTO,
       COUNT(*) AS TOTAL,
	   COUNT(DISTINCT CNPJ) AS TOTAL_CNPJ,
       SUM(VALOR_CONTRATO) AS VALOR_CONTRATO,
	   SUM(VALOR_DESEMBOLSO) AS VALOR_DESEMBOLSO,
	   SUM(JUROS_CONTRATO) AS JUROS_CONTRATO,
	   AVG(JUROS) AS JUROS,
	   SUM(JUROS_CONTRATO)/SUM(VALOR_CONTRATO) AS JUROS_PESO,
	   SUM(AMORTIZACAO_CONTRATO)/SUM(VALOR_CONTRATO) AS AMORTIZACAO_PESO,
	   AVG(PRAZO_AMORTIZACAO) AS PRAZO_AMORTIZACAO

FROM NAOAUTOM
GROUP BY CUSTO_FINANCEIRO,DATA_MOVIMENTO
ORDER BY CUSTO_FINANCEIRO,DATA_MOVIMENTO;
QUIT;





PROC SQL NOPRINT;
CREATE TABLE INOVA_AUTOM AS
SELECT INOVACAO,
       DATA_MOVIMENTO,
       COUNT(*) AS TOTAL,
	   COUNT(DISTINCT CNPJ) AS TOTAL_CNPJ,
       SUM(VALOR_CONTRATO) AS VALOR_CONTRATO,
	   SUM(VALOR_DESEMBOLSO) AS VALOR_DESEMBOLSO,
	   SUM(JUROS_CONTRATO) AS JUROS_CONTRATO,
	   AVG(JUROS) AS JUROS,
	   SUM(JUROS_CONTRATO)/SUM(VALOR_CONTRATO) AS JUROS_PESO,
	   SUM(AMORTIZACAO_CONTRATO)/SUM(VALOR_CONTRATO) AS AMORTIZACAO_PESO,
	   AVG(PRAZO_AMORTIZACAO) AS PRAZO_AMORTIZACAO

FROM AUTOM
GROUP BY INOVACAO,DATA_MOVIMENTO
ORDER BY INOVACAO,DATA_MOVIMENTO;

CREATE TABLE INOVA_NAOAUTOM AS
SELECT INOVACAO,
       DATA_MOVIMENTO,
       COUNT(*) AS TOTAL,
	   COUNT(DISTINCT CNPJ) AS TOTAL_CNPJ,
       SUM(VALOR_CONTRATO) AS VALOR_CONTRATO,
	   SUM(VALOR_DESEMBOLSO) AS VALOR_DESEMBOLSO,
	   SUM(JUROS_CONTRATO) AS JUROS_CONTRATO,
	   AVG(JUROS) AS JUROS,
	   SUM(JUROS_CONTRATO)/SUM(VALOR_CONTRATO) AS JUROS_PESO,
	   SUM(AMORTIZACAO_CONTRATO)/SUM(VALOR_CONTRATO) AS AMORTIZACAO_PESO,
	   AVG(PRAZO_AMORTIZACAO) AS PRAZO_AMORTIZACAO

FROM NAOAUTOM
GROUP BY INOVACAO,DATA_MOVIMENTO
ORDER BY INOVACAO,DATA_MOVIMENTO;
QUIT;


