LIBNAME REC "/dados/RISCO/Modelagem_Nas/Risco_de_Credito/Fraude/Receita";

PROC CONTENTS DATA=REC.INDIRETAS_AUTOMATICAS OUT=C(KEEP=NAME) NOPRINT;RUN;
PROC CONTENTS DATA=REC.NAOAUTOMATICAS        OUT=C(KEEP=NAME) NOPRINT;RUN;


PROC SQL NOPRINT;
CREATE TABLE BNDES AS
SELECT FORMA_APOIO,
       COUNT(*) AS TOTAL,
       SUM(VALOR_CONTRATO) AS VALOR_CONTRATO,
	   SUM(PRAZO_CARENCIA) AS SOMA_JUROS

FROM REC.FORMA_APOIO
GROUP BY CUSTO_FINANCEIRO
ORDER BY CUSTO_FINANCEIRO;
QUIT;




PROC SQL NOPRINT;
CREATE TABLE BNDES AS
SELECT CUSTO_FINANCEIRO,INOVACAO,FORMA_APOIO,SITUACAO_CONTRATO,
       YEAR(DATA_CONTRATO) AS ANO,
	   MONTH(DATA_CONTRATO) AS MES,
       SUM(VALOR_CONTRATO) AS VALOR_CONTRATO,
	   SUM(PRAZO_CARENCIA) AS SOMA_JUROS,
	   AVG(PRAZO_AMORTIZACAO) AS PRAZO_AMORTIZACAO

FROM RECEITA.BNDES
GROUP BY CUSTO_FINANCEIRO,INOVACAO,FORMA_APOIO,SITUACAO_CONTRATO,ANO;
QUIT;


