

PROC SQL;
CREATE TABLE RAROC_VEICULOS_CPF AS
SELECT DISTINCT  A.CNPJ14,CD_CON,
       VR_LBR,QT_DD_ATS_PRL,QT_PRL,PC_TX_JRO,VR_PVS,
	   B.PD/100 AS PD
       MAX(VR_SLD_DVD) AS VR_SLD_DVD,
       CASE WHEN AVG(b.PD)<=0.22 THEN 'AA'
		    WHEN AVG(b.PD)<=0.70 THEN 'A'
		    WHEN AVG(b.PD)<=1.03 THEN 'B'
		    WHEN AVG(b.PD)<=2.07 THEN 'C'
			WHEN AVG(b.PD)<=5.46 THEN 'D'
			WHEN AVG(b.PD)<=20   THEN 'E'
			WHEN AVG(b.PD)<=60   THEN 'F'
			WHEN AVG(b.PD)<=85   THEN 'G'
			WHEN AVG(b.PD)<=100  THEN 'H'
			ELSE '' END AS RISCO_BC ,
	    CASE WHEN QT_DD_ATS_PRL>90 THEN VR_SLD_DVD ELSE 0 END AS VR_SLD_DVD90

   FROM 
      ( SELECT DISTINCT CNPJ14,QT_DD_ATS_PRL,CD_CON,DT_MVM_DWM,
                        PC_TX_JRO,QT_PRL,VR_LBR,VR_PVS,VR_SLD_DVD,
						MAX(DT_MVM_DWM) OVER (PARTITION BY CNPJ14,CD_CON) 
                        AS DATA_MAX 

        FROM MOVIMENTO_OPERACAO
        WHERE DS_MDL_BACEN='FINANCIAMENTOS' 
              AND DS_SUB_MDL_BACEN='AQUISIÇÃO DE BENS – VEÍCULOS AUTOMOTORES' 
              AND CD_MDL_BACEN=4 
              AND CD_SUB_MDL_BACEN = 1
              AND DT_MVM_DWM > '2019-03-01' 
			  AND DT_LBR> '2018-01-01' 
              AND PC_TX_JRO>0 
              AND IC_MVM = 1 
              AND CD_NVL_RCO NOT IN ('HH')
			  AND DS_TPO_PSS='PF'
        ORDER BY CNPJ14 
        ) AS A
		LEFT JOIN PLD.PD_COP_MARCO19_23_04 AS B ON (A.CNPJ14=B.CNPJ14 )
		WHERE B.PD NE . AND A.DT_MVM_DWM = A.DATA_MAX
        GROUP BY A.CNPJ14,VR_LBR,QT_DD_ATS_PRL,
                 VR_PVS,QT_PRL,PC_TX_JRO,B.PD,CD_CON

        ORDER BY A.CNPJ14 ;
QUIT;




/*--------------------------------------------------------------------------*/
/*---           RAROC DA CARTEIRA DE FINANCIAMENTO DE VEÍCULOS           ---*/
/*--------------------------------------------------------------------------*/


PROC SQL;
   CREATE TABLE RAROC_VEICULOS_CPF AS
   SELECT CNPJ14,CD_CON,CNAE,DT_MVM_DWM,
          VR_LBR,QT_DD_ATS_PRL,QT_PRL,DS_NVL_RCO,PC_TX_JRO,
		  AVG(PD)/100 AS PD,
          AVG(DESVIO_PERDA)/100 AS DESVIO_PERDA,
          MAX(VR_SLD_DVD) AS VR_SLD_DVD,
		  MAX((PC_TX_JRO/100)*VR_SLD_DVD) as NUM_PC_TX_JRO,
		  CASE WHEN QT_DD_ATS_PRL>90 THEN VR_SLD_DVD ELSE 0 END AS VR_SLD_DVD90

   FROM CONNECTION TO con1 
      ( SELECT DISTINCT CNPJ14,CNAE,VR_LBR,QT_DD_ATS_PRL,
                        DT_MVM_DWM,PC_TX_JRO,QT_PRL,VR_SLD_DVD,CD_CON,DS_NVL_RCO,
						MAX(DT_MVM_DWM) OVER (PARTITION BY CNPJ14,CNAE) AS DATA_MAX ,
						CASE WHEN DS_NVL_RCO='R1'  THEN 0.220
		                     WHEN DS_NVL_RCO='R2'  THEN 0.480
		                     WHEN DS_NVL_RCO='R3'  THEN 0.700
			                 WHEN DS_NVL_RCO='R4'  THEN 1.030
			                 WHEN DS_NVL_RCO='R5'  THEN 2.070
			                 WHEN DS_NVL_RCO='R6'  THEN 3.220
			                 WHEN DS_NVL_RCO='R7'  THEN 5.460
			                 WHEN DS_NVL_RCO='R8'  THEN 7.000
			                 WHEN DS_NVL_RCO='R9'  THEN 10.46
							 WHEN DS_NVL_RCO='R10' THEN 13.00
							 WHEN DS_NVL_RCO='R11' THEN 15.60
							 WHEN DS_NVL_RCO='R12' THEN 20.00
                             WHEN DS_NVL_RCO='R13' THEN 25.00
							 WHEN DS_NVL_RCO='R14' THEN 30.00
							 WHEN DS_NVL_RCO='R15' THEN 40.00
							 WHEN DS_NVL_RCO='R16' THEN 50.00
							 WHEN DS_NVL_RCO='R17' THEN 60.00
							 WHEN DS_NVL_RCO='R18' THEN 70.00
							 WHEN DS_NVL_RCO='R19' THEN 85.00
							 WHEN DS_NVL_RCO='R20' THEN 100.0
			                 END AS PD,

					    CASE WHEN DS_NVL_RCO='R1'  THEN 6.020
		                     WHEN DS_NVL_RCO='R2'  THEN 8.650
		                     WHEN DS_NVL_RCO='R3'  THEN 12.62
			                 WHEN DS_NVL_RCO='R4'  THEN 12.62
			                 WHEN DS_NVL_RCO='R5'  THEN 20.32
			                 WHEN DS_NVL_RCO='R6'  THEN 25.24
			                 WHEN DS_NVL_RCO='R7'  THEN 67.01
			                 WHEN DS_NVL_RCO='R8'  THEN 67.01
			                 WHEN DS_NVL_RCO='R9'  THEN 87.75
							 WHEN DS_NVL_RCO='R10' THEN 241.4 
							 WHEN DS_NVL_RCO='R11' THEN 241.4
							 WHEN DS_NVL_RCO='R12' THEN 241.4
							 WHEN DS_NVL_RCO='R13' THEN 241.4
							 WHEN DS_NVL_RCO='R14' THEN 241.4
							 WHEN DS_NVL_RCO='R15' THEN 341.6
							 WHEN DS_NVL_RCO='R16' THEN 452.7
							 WHEN DS_NVL_RCO='R17' THEN 478.2
							 WHEN DS_NVL_RCO='R18' THEN 478.2
							 WHEN DS_NVL_RCO='R19' THEN 865.7
							 WHEN DS_NVL_RCO='R20' THEN 1450.3
                             END AS DESVIO_PERDA

        FROM MOVIMENTO_OPERACAO
        WHERE DS_MDL_BACEN='FINANCIAMENTOS' 
              AND DS_SUB_MDL_BACEN='AQUISIÇÃO DE BENS – VEÍCULOS AUTOMOTORES' 
              AND CD_MDL_BACEN=4 
              AND CD_SUB_MDL_BACEN=1
              AND DT_MVM_DWM >'2018-01-01' 
			  AND DT_LBR >'2017-01-01' 
              AND PC_TX_JRO>0 
              AND IC_MVM = 1 
              AND CNAE<>1
              AND CD_NVL_RCO<>'HH'
			  AND DS_NVL_RCO NOT IN ('N/A','R99')
			  AND DS_TPO_PSS='PF'
        ORDER BY CNPJ14,CNAE 
        ) 
		
		WHERE DT_MVM_DWM = DATA_MAX
        GROUP BY CNPJ14,CNAE,VR_LBR,QT_DD_ATS_PRL,
                 DT_MVM_DWM,QT_PRL,DS_NVL_RCO,PC_TX_JRO,CD_CON
        ORDER BY CNPJ14,CNAE,CD_CON ;
QUIT;


PROC SQL;
   CREATE TABLE COV_VAR_RAROC as
   SELECT CNPJ14,CD_CON,CNAE,RISCO_BC,
          SUM(VR_SLD_DVD*PD) AS PERDA,
		  SUM(VR_SLD_DVD) AS VR_SLD_DVD,
		  SUM(VR_SLD_DVD90) AS VR_SLD_DVD90,
		  SUM(VR_PVS) AS VR_PVS,
		  SUM(VR_SLD_DVD90)/SUM(VR_SLD_DVD) AS INAD90,
		  SUM(VR_PVS)/SUM(VR_SLD_DVD) AS IPROV,
		  1 AS CONTAGEM
   FROM RAROC_VEICULOS_CPF 
   GROUP BY CNPJ14,CD_CON,CNAE,RISCO_BC
   ORDER BY CNPJ14,CD_CON,CNAE,RISCO_BC;   
QUIT;


/*PERDA ESPERADA E DESVIO-PADRÃO DA PERDA ESPERADA*/
PROC MEANS DATA=COV_VAR_RAROC NOPRINT NWAY;
CLASS RISCO_BC;
OUTPUT OUT=SAIDA(DROP=_FREQ_ _TYPE_) 
       SUM(CONTAGEM)=SALDO_TOTAL 
	   MEAN(PERDA)=PERDA_MEDIA

	   STD(PERDA)=PERDA_STD
	   P95(PERDA)=PERDA_P95
	   P99(PERDA)=PERDA_P99

       STD(IPROV)=STD_IPROV
	   P95(IPROV)=IPROV_P95
	   P99(IPROV)=IPROV_P99

	   STD(VR_PVS)=STD_VR_PVS
	   P95(VR_PVS)=VR_PVS_P95
	   P99(VR_PVS)=VR_PVS_P99 ;
WEIGHT VR_SLD_DVD;
RUN;


/*-------------------------------------------------------------*/
/*-------------------------------------------------------------*/
/*---                 ABORDAGEM EMPÍRICA                    ---*/
/*-------------------------------------------------------------*/
/*-------------------------------------------------------------*/
/*---      QUANTIL NÃO PARAMÉTRICO DOS SALDOS POR RISCO     ---*/
/*-------------------------------------------------------------*/
/*-------------------------------------------------------------*/



PROC SORT DATA=RAROC_VEICULOS_CPF SORTSIZE=MAX;BY DS_NVL_RCO;RUN;
PROC STANDARD
  DATA=RAROC_VEICULOS_CPF(KEEP=CNPJ14 DS_NVL_RCO VR_SLD_DVD)
  MEAN=0 STD=1 REPLACE NOPRINT OUT=SCORE;
  BY DS_NVL_RCO;
  VAR VR_SLD_DVD;
RUN;

PROC MEANS DATA=SCORE NOPRINT NWAY;
CLASS DS_NVL_RCO;
OUTPUT OUT=TESTE(DROP=_FREQ_ _TYPE_) 
       P95(VR_SLD_DVD)=P95_SLD_DVD90
       P99(VR_SLD_DVD)=P99_SLD_DVD90;
RUN;





OPTIONS COMPRESS=YES;
PROC SQL;
CREATE TABLE FINAN_CARROS AS 
  SELECT DT_MVM_DWM,
         CD_NVL_RCO,
		 COUNT(*) AS QTD_OPERACOES,
		 SUM(VR_SLD_DVD) AS VALOR_OPERACOES,
		 SUM(NUM_PC_TX_JRO)/SUM(VR_SLD_DVD) AS TAXA_JUROS,
         QT_PRL AS PRAZO,
		 SUM(VR_SLD_DVD)*((1+CALCULATED TAXA_JUROS)**QT_PRL) AS VALOR_FINAL,
		 SUM(VR_SLD_DVD)*(((1+CALCULATED TAXA_JUROS)**QT_PRL)*CALCULATED TAXA_JUROS)/(((1+CALCULATED TAXA_JUROS)**QT_PRL)-1) AS PRESTACAO_PRICE,
		 SUM(VR_SLD_DVD)*(1+0.07) AS CUSTO_CAPTACAO,
		 QT_PRL*CALCULATED PRESTACAO_PRICE AS MONTANTE_NOMINAL,
		 10*COUNT(*) AS TAXAS_COMISSOES,
		 0.03*CALCULATED MONTANTE_NOMINAL AS CUSTOS_OPERACIONAIS,
		 MEAN(PD/100) AS PERDA_ESPERADA,
		 DESVIO_PERDA/100 AS DESVIO_PERDA,
		 (MEAN(PD)/100)*CALCULATED MONTANTE_NOMINAL AS VALOR_PERDA_ESPERADA,
		 CALCULATED MONTANTE_NOMINAL-CALCULATED CUSTO_CAPTACAO AS SPREAD,
		 CALCULATED SPREAD+CALCULATED TAXAS_COMISSOES-CALCULATED CUSTOS_OPERACIONAIS-CALCULATED VALOR_PERDA_ESPERADA  AS LUCRO_AJUSTADO,
		 2.33 AS NIVEL_CONFIANCA,
		 2.33*(DESVIO_PERDA/100)*SUM(VR_SLD_DVD) AS PERDA_INESPERADA

      FROM RAROC_VEICULOS_CPF AS A
      GROUP BY DT_MVM_DWM,CD_NVL_RCO,QT_PRL,DESVIO_PERDA
	  ORDER BY DT_MVM_DWM,CD_NVL_RCO;
QUIT;


