
PROC SQL NOPRINT;
CREATE TABLE SELIC(COMPRESS=YES) AS
SELECT DISTINCT MONTH(DATAX) AS MES,YEAR(DATAX) AS ANO,SELIC/100 AS SELIC
FROM REC.SELIC
ORDER BY ANO,MES;

CREATE TABLE TJLP(COMPRESS=YES) AS
SELECT DISTINCT DAY(DATAX) AS MES,YEAR(DATAX) AS ANO,TJLP/100 AS TJLP
FROM REC.TJLP
ORDER BY ANO,MES;

CREATE TABLE TLP(COMPRESS=YES) AS
SELECT DISTINCT DAY(DATA) AS MES,YEAR(DATA) AS ANO,TLP/100 AS TLP
FROM REC.TLP
ORDER BY ANO,MES;
QUIT;


/*--------------------------------------------------------------------------*/
/*---  ETAPAS PARA CALCULO DO RAROC DA CARTEIRA DE FINANCIAMENTO BNDES   ---*/
/*--------------------------------------------------------------------------*/

PROC SQL;
CREATE TABLE RAROC_BNDES(COMPRESS=YES) AS
SELECT DISTINCT A.EMPRESA,A.PRODUTO,A.DATA_CONTRATO,A.PORTE_CLIENTE,
       A.PRAZO_AMORTIZACAO AS QT_PRL,A.VALOR_CONTRATO,B.NIVEL_RISCO,
       Fonte_Recurso,B.PROBA,CNPJ_INSTITUICAO,SELIC/12 AS SELIC,
	   CASE WHEN CUSTO_FINANCEIRO LIKE "%SELIC%" THEN A.JUROS/12 + C.SELIC/12
            WHEN CUSTO_FINANCEIRO LIKE "%TJLP%"  THEN A.JUROS/12 + D.TJLP/12
			WHEN CUSTO_FINANCEIRO LIKE "%TJLP%"  THEN A.JUROS/12 + E.TLP/12
            ELSE A.JUROS/100 END AS TAXA_JUROS

FROM REC.BNDES AS A
INNER JOIN REC.BNDES_RAROC AS B ON A.EMPRESA=B.CNPJ8 AND YEAR(A.DATA_CONTRATO)=B.ANO
LEFT  JOIN SELIC           AS C ON MONTH(A.DATA_CONTRATO)=C.MES AND YEAR(A.DATA_CONTRATO)=C.ANO
INNER JOIN TJLP            AS D ON YEAR(A.DATA_CONTRATO)=D.ANO AND MONTH(A.DATA_CONTRATO)=D.MES
INNER JOIN TLP             AS E ON YEAR(A.DATA_CONTRATO)=E.ANO AND MONTH(A.DATA_CONTRATO)=E.MES
WHERE A.JUROS>0 AND A.PRAZO_AMORTIZACAO>0
ORDER BY A.EMPRESA;
QUIT;


PROC SQL;
CREATE TABLE COV_VAR AS
SELECT CNPJ_INSTITUICAO,
       MAX(CASE WHEN NIVEL_RISCO=1  THEN VALOR_CONTRATO ELSE 0 END) AS SLD_DVD_1,
       MAX(CASE WHEN NIVEL_RISCO=2  THEN VALOR_CONTRATO ELSE 0 END) AS SLD_DVD_2,
       MAX(CASE WHEN NIVEL_RISCO=3  THEN VALOR_CONTRATO ELSE 0 END) AS SLD_DVD_3,
       MAX(CASE WHEN NIVEL_RISCO=4  THEN VALOR_CONTRATO ELSE 0 END) AS SLD_DVD_4,
       MAX(CASE WHEN NIVEL_RISCO=5  THEN VALOR_CONTRATO ELSE 0 END) AS SLD_DVD_5,
       MAX(CASE WHEN NIVEL_RISCO=6  THEN VALOR_CONTRATO ELSE 0 END) AS SLD_DVD_6,
       MAX(CASE WHEN NIVEL_RISCO=7  THEN VALOR_CONTRATO ELSE 0 END) AS SLD_DVD_7,
       MAX(CASE WHEN NIVEL_RISCO=8  THEN VALOR_CONTRATO ELSE 0 END) AS SLD_DVD_8,
       MAX(CASE WHEN NIVEL_RISCO=9  THEN VALOR_CONTRATO ELSE 0 END) AS SLD_DVD_9

FROM RAROC_BNDES
GROUP BY CNPJ_INSTITUICAO
ORDER BY CNPJ_INSTITUICAO;
QUIT;



PROC CORR DATA=COV_VAR NOPRINT OUT=CORREL(WHERE=(_TYPE_='CORR'));
WHERE SLD_DVD_1>0;
VAR SLD_DVD_:;
RUN;

/*--------------------------------------------------------------------------*/
/*---  PERCENTUAL DE PERDA E DESVIO PADRAO DA PERDA ESPERADA             ---*/
/*--------------------------------------------------------------------------*/
DATA PD;
INPUT NIVEL_RISCO PD;
STD_PD=(1+PD)*(1+PD);
CARDS;
1  0.001
2  0.005
3  0.010
4  0.030
5  0.100
6  0.300
7  0.500
8  0.700
9  1.000
;
RUN;


/*PERDA ESPERADA E DESVIO-PADRÃO DA PERDA ESPERADA*/
PROC SORT DATA=RAROC_BNDES SORTSIZE=MAX;BY NIVEL_RISCO;RUN;
PROC MEANS DATA=RAROC_BNDES NOPRINT NWAY;
BY NIVEL_RISCO;
OUTPUT OUT=SAIDA(DROP=_FREQ_) MEAN(VALOR_CONTRATO)=VR_MEDIA STD(VALOR_CONTRATO)=VR_STD;
RUN;


PROC SQL;
CREATE TABLE ZSCORE(COMPRESS=YES) AS
SELECT DISTINCT EMPRESA,DATA_CONTRATO,A.NIVEL_RISCO,
       (VALOR_CONTRATO-VR_MEDIA)/VR_STD AS Z_SLD_DVD,
	   PROBA*VALOR_CONTRATO AS PERDA_ESPERADA

FROM RAROC_BNDES AS A
INNER JOIN SAIDA AS B ON A.NIVEL_RISCO=B.NIVEL_RISCO
INNER JOIN PD    AS C ON A.NIVEL_RISCO=C.NIVEL_RISCO;
QUIT;


PROC SORT DATA=ZSCORE SORTSIZE=MAX;BY NIVEL_RISCO;RUN;
PROC MEANS DATA=ZSCORE NOPRINT NWAY;
BY NIVEL_RISCO;
OUTPUT OUT=QUANTIL(DROP=_FREQ_ _TYPE_) P95(Z_SLD_DVD)=QPROV95 P99(Z_SLD_DVD)=QPROV99;
RUN;


OPTIONS COMPRESS=YES;
PROC SQL;
CREATE TABLE RAROC_BNDES2 AS 
SELECT DISTINCT A.EMPRESA,A.DATA_CONTRATO,A.PORTE_CLIENTE,A.NIVEL_RISCO,CNPJ_INSTITUICAO,Fonte_Recurso,
       VALOR_CONTRATO*(((1+TAXA_JUROS)**QT_PRL)*TAXA_JUROS)/(((1+TAXA_JUROS)**QT_PRL)-1) AS PRESTACAO_PRICE,
       VALOR_CONTRATO*SELIC AS CUSTO_CAPTACAO,
       QT_PRL*CALCULATED PRESTACAO_PRICE AS MONTANTE_NOMINAL,
       0.03*CALCULATED MONTANTE_NOMINAL AS CUSTOS_OPERACIONAIS,
       PD*CALCULATED MONTANTE_NOMINAL AS PERDA_ESPERADA,
       CALCULATED MONTANTE_NOMINAL-CALCULATED CUSTO_CAPTACAO AS SPREAD,
       CALCULATED SPREAD-CALCULATED CUSTOS_OPERACIONAIS-CALCULATED PERDA_ESPERADA AS LUCRO_AJUSTADO,
       QPROV99*CALCULATED MONTANTE_NOMINAL AS PERDA_INESPERADA

      FROM RAROC_BNDES AS A
	  LEFT JOIN PD      AS B ON A.NIVEL_RISCO=B.NIVEL_RISCO 
	  LEFT JOIN QUANTIL AS C ON A.NIVEL_RISCO=C.NIVEL_RISCO  ;
QUIT;




/*--------------------------------------------------------------------------*/
/*---           RAROC DA CARTEIRA DE FINANCIAMENTO DE VEÍCULOS           ---*/
/*--------------------------------------------------------------------------*/

PROC SORT DATA=RAROC_BNDES SORTSIZE=MAX;BY NIVEL_RISCO;RUN;
PROC SORT DATA=PD          SORTSIZE=MAX;BY NIVEL_RISCO;RUN;
PROC SORT DATA=QUANTIL     SORTSIZE=MAX;BY NIVEL_RISCO;RUN;
DATA RAROC_BNDES3;
MERGE RAROC_BNDES PD QUANTIL;
BY NIVEL_RISCO;
VALOR_OPERACOES       = VALOR_CONTRATO;
PRAZO                 = QT_PRL;
GARANTIA              = 0.25;
VALOR_FINAL           = VALOR_OPERACOES*((1+TAXA_JUROS)**PRAZO);
PRESTACAO_FORMULA     = VALOR_OPERACOES*((((1+TAXA_JUROS)**PRAZO)*TAXA_JUROS)/(((1+TAXA_JUROS)**PRAZO)-1));
PRESTACAO_PRICE       = FINANCE('pmt',TAXA_JUROS,PRAZO,-VALOR_OPERACOES,0);
SELIC_PRAZO           = ((1+SELIC)**(PRAZO))-1;
CUSTO_CAPTACAO        = VALOR_OPERACOES*(1+SELIC_PRAZO);
MONTANTE_NOMINAL      = PRAZO*PRESTACAO_PRICE;
CUSTOS_OPER           = 0.03*MONTANTE_NOMINAL;
DESVIO_PERDA_ESPERADA = QPROV99*(1-GARANTIA)*MONTANTE_NOMINAL;
PERDA_ESPERADA        = PD*MONTANTE_NOMINAL;
SPREAD                = MONTANTE_NOMINAL-CUSTO_CAPTACAO;
LUCRO_AJUSTADO        = SPREAD-CUSTOS_OPER-PERDA_ESPERADA;
VAR                   = PERDA_ESPERADA+(1-GARANTIA)*DESVIO_PERDA_ESPERADA;
RAROC                 = LUCRO_AJUSTADO/VAR;
RUN;




PROC MEANS DATA=RAROC_BNDES3 NOPRINT;
BY NIVEL_RISCO;
OUTPUT OUT=DIST 
P1(RAROC)=RAROC_1 P25(RAROC)=RAROC_P25 P50(RAROC)=RAROC_MED P75(RAROC)=RAROC_P75 P99(RAROC)=RAROC_99;
RUN;


PROC MEANS DATA=RAROC_BNDES3 NOPRINT;
CLASS PORTE_CLIENTE;
OUTPUT OUT=DIST 
P1(RAROC)=RAROC_1 P25(RAROC)=RAROC_P25 P50(RAROC)=RAROC_MED P75(RAROC)=RAROC_P75 P99(RAROC)=RAROC_99;
RUN;

PROC MEANS DATA=RAROC_BNDES3 NOPRINT NWAY;
CLASS Fonte_Recurso;
OUTPUT OUT=DIST 
P1(RAROC)=RAROC_1 P25(RAROC)=RAROC_P25 P50(RAROC)=RAROC_MED P75(RAROC)=RAROC_P75 P99(RAROC)=RAROC_99;
RUN;

PROC SQL;
CREATE TABLE RAROC_RATING AS 
  SELECT NIVEL_RISCO,
         SUM(LUCRO_AJUSTADO) AS LUCRO_AJUSTADO,
		 SUM(LUCRO_AJUSTADO)/SUM(PERDA_INESPERADA) AS RAROC
  FROM RAROC_BNDES3
  GROUP BY NIVEL_RISCO
  ORDER BY NIVEL_RISCO;

CREATE TABLE RAROC_PORTE AS 
SELECT PORTE_CLIENTE,
       SUM(LUCRO_AJUSTADO) AS LUCRO_AJUSTADO,
       SUM(LUCRO_AJUSTADO)/SUM(PERDA_INESPERADA) AS RAROC
  FROM RAROC_BNDES3
  GROUP BY PORTE_CLIENTE
  ORDER BY PORTE_CLIENTE;

CREATE TABLE RAROC_INSTITUICAO AS 
SELECT Fonte_Recurso,
       SUM(LUCRO_AJUSTADO) AS LUCRO_AJUSTADO,
       SUM(PERDA_INESPERADA) AS PERDA_INESPERADA,
       SUM(LUCRO_AJUSTADO)/SUM(PERDA_ESPERADA+PERDA_INESPERADA) AS RAROC
  FROM RAROC_BNDES3
  GROUP BY Fonte_Recurso
  ORDER BY Fonte_Recurso;
QUIT;
